### ISSUE TITLE
Feature : Error Boundary

### ISSUE THREAD

**Issue by sulaimon23** [super-demo/mini-translator#35]
Create error Boundary component to catch unexpected errors and prevent application from looking broken.

Steps to create: 
-- If .env variable is missing. whole app breaks.

<img width="1146" alt="Screenshot 2024-11-25 at 9 01 22 PM" src="https://github.com/user-attachments/assets/3f2f50d4-8d08-4b95-a983-18263a0d6cf8">

**Comment by nopnapatn** [comment]
Why it should can run without .env file?

**Comment by sulaimon23** [comment]
No. I am not saying it should run without .env. 

I am saying uncaught error should be handled.

**Comment by nopnapatn** [comment]
ahh, I see sorry
